# Generated by Django 5.2.13 on 2026-04-26 09:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10, unique=True, verbose_name='客户编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['customer_code'],
            },
        ),
        migrations.CreateModel(
            name='FAETaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': 'FAE任务评论',
                'verbose_name_plural': 'FAE任务评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAETaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': 'FAE任务日志',
                'verbose_name_plural': 'FAE任务日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_updated', '任务更新'), ('task_commented', '任务评论'), ('task_status_changed', '状态变更'), ('task_reviewed', '任务审核')], max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(blank=True, verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('fae', 'FAE工程师'), ('fae_leader', 'FAE主管'), ('rd', '研发工程师'), ('rd_leader', '研发主管'), ('warehouse', '仓库管理员'), ('admin', '管理员')], default='fae', max_length=20, verbose_name='角色')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FAETask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='任务编号')),
                ('task_type', models.CharField(choices=[('test_tracking', '测试跟踪'), ('abnormal_tracking', '异常跟踪'), ('customer_comm', '客户沟通'), ('first_piece_test', '首件测试')], max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('pending_review', '待审核'), ('completed', '已结束'), ('paused', '暂停中')], default='not_started', max_length=20, verbose_name='任务状态')),
                ('summary', models.CharField(help_text='任务的简短概述或标题', max_length=200, verbose_name='任务概述')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='任务描述')),
                ('result', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='任务结论')),
                ('review_result', models.CharField(choices=[('pending', '待审核'), ('passed', '通过'), ('rejected', '不通过')], default='pending', max_length=20, verbose_name='审核结果')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(limit_choices_to={'role__in': ['fae', 'fae_leader']}, on_delete=django.db.models.deletion.CASCADE, related_name='fae_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fae_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fae.customer', verbose_name='所属客户')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': 'FAE任务',
                'verbose_name_plural': 'FAE任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
