# Generated by Django 5.2.13 on 2026-04-26 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fae', '0001_initial'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faetask',
            name='test_items',
            field=models.ManyToManyField(blank=True, related_name='fae_tasks', to='testing.testitem', verbose_name='测试项'),
        ),
        migrations.AddField(
            model_name='faetaskcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='faetaskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fae.faetask', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='faetasklog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='faetasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fae.faetask', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送人'),
        ),
        migrations.AddField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fae.faetask', verbose_name='相关任务'),
        ),
    ]
