# Generated by Django 6.0.3 on 2026-05-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fae', '0003_faetask_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnalyzerKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='关键词名称')),
                ('pattern', models.CharField(help_text='支持普通文本或正则表达式', max_length=500, verbose_name='匹配内容')),
                ('regex', models.BooleanField(default=False, verbose_name='是否正则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '日志分析关键词',
                'verbose_name_plural': '日志分析关键词',
                'ordering': ['order', 'id'],
            },
        ),
    ]
