# Generated by Django 5.2.13 on 2026-08-27 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fae', '0004_loganalyzerkeyword'),
        ('project', '0008_productionplan_production_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faetask',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fae_tasks', to='project.productionplan', verbose_name='生产方案'),
        ),
    ]
