# Generated by Django 6.0.3 on 2026-07-16 09:50

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abnormal', '0006_abnormalsample_abnormal_summary_and_more'),
        ('project', '0003_delete_activitytimeline'),
        ('solution', '0002_solution_project'),
        ('testing', '0014_testparameterdefinition_default_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='问题单编号')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1')], default='p1', max_length=10, verbose_name='优先级')),
                ('diagnosis_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='诊断记录')),
                ('root_cause', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='根因结果')),
                ('solution_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='解决方案')),
                ('verification_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='验证记录')),
                ('status', models.CharField(choices=[('pending', '未处理'), ('processing', '处理中'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='问题单状态')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('abnormal_samples', models.ManyToManyField(blank=True, related_name='issues', to='abnormal.abnormalsample', verbose_name='异常样品')),
                ('diagnosis_tests', models.ManyToManyField(blank=True, related_name='diagnosis_issues', to='testing.testitem', verbose_name='诊断记录关联测试项')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='project.project', verbose_name='所属项目')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='solution.solution', verbose_name='关联方案')),
                ('submitter', models.ForeignKey(limit_choices_to={'role__in': ['fae', 'fae_leader']}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_issues', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('verification_tests', models.ManyToManyField(blank=True, related_name='verification_issues', to='testing.testitem', verbose_name='验证记录关联测试项')),
            ],
            options={
                'verbose_name': '问题单',
                'verbose_name_plural': '问题单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='issue.issue', verbose_name='问题单')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '问题单日志',
                'verbose_name_plural': '问题单日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
