# Generated by Django 6.0.3 on 2026-07-16 10:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
        ('project', '0003_delete_activitytimeline'),
        ('solution', '0002_solution_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='abnormal_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='异常描述'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='solution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='solution.solution', verbose_name='关联方案'),
        ),
    ]
