# Generated by Django 6.0.3 on 2026-07-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_abnormal_description_alter_issue_project_and_more'),
        ('project', '0003_delete_activitytimeline'),
        ('solution', '0002_solution_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='solution.solution', verbose_name='关联方案'),
        ),
    ]
