# Generated by Django 6.0.3 on 2026-07-16 10:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_issue_project_alter_issue_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='abnormal_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='异常描述'),
        ),
    ]
