# Generated by Django 6.0.3 on 2026-07-17 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_remove_issue_diagnosis_content_and_more'),
        ('testing', '0014_testparameterdefinition_default_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTroubleshootingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('text', '文本'), ('test_item', '测试项')], default='text', max_length=20, verbose_name='记录类型')),
                ('content', models.TextField(blank=True, verbose_name='记录内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troubleshooting_records', to='issue.issue', verbose_name='问题单')),
                ('test_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleshooting_records', to='testing.testitem', verbose_name='关联测试项')),
            ],
            options={
                'verbose_name': '排查记录',
                'verbose_name_plural': '排查记录',
                'ordering': ['created_at'],
            },
        ),
    ]
