# Generated by Django 6.0.3 on 2026-07-23 02:05

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0006_abnormalsample_abnormal_summary_and_more'),
        ('issue', '0006_issuetroubleshootingrecord'),
        ('testing', '0014_testparameterdefinition_default_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuetroubleshootingrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='issuetroubleshootingrecord',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuetroubleshootingrecord',
            name='test_item',
        ),
        migrations.RemoveField(
            model_name='issueverificationrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='issueverificationrecord',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issueverificationrecord',
            name='test_item',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='abnormal_samples',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='root_cause',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='solution_content',
        ),
        migrations.CreateModel(
            name='IssueSolutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('text', '文本'), ('test_item', '测试项'), ('abnormal_sample', '异常样品')], default='text', max_length=20, verbose_name='记录类型')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='记录内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('abnormal_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_records', to='abnormal.abnormalsample', verbose_name='关联异常样品')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_records', to='issue.issue', verbose_name='问题单')),
                ('test_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_records', to='testing.testitem', verbose_name='关联测试项')),
            ],
            options={
                'verbose_name': '问题解决记录',
                'verbose_name_plural': '问题解决记录',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='IssueDiagnosisRecord',
        ),
        migrations.DeleteModel(
            name='IssueTroubleshootingRecord',
        ),
        migrations.DeleteModel(
            name='IssueVerificationRecord',
        ),
    ]
