# Generated by Django 6.0.3 on 2026-07-23 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0006_abnormalsample_abnormal_summary_and_more'),
        ('issue', '0007_remove_issuetroubleshootingrecord_created_by_and_more'),
        ('testing', '0014_testparameterdefinition_default_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuesolutionrecord',
            name='abnormal_sample',
        ),
        migrations.RemoveField(
            model_name='issuesolutionrecord',
            name='content',
        ),
        migrations.RemoveField(
            model_name='issuesolutionrecord',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='issuesolutionrecord',
            name='test_item',
        ),
        migrations.AddField(
            model_name='issuesolutionrecord',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='记录标题'),
        ),
        migrations.AlterField(
            model_name='issuesolutionrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='issuesolutionrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.CreateModel(
            name='IssueSolutionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('troubleshooting', '排查记录'), ('abnormal_sample', '异常样品'), ('root_cause', '根因结果'), ('solution', '解决方案'), ('verification', '验证记录')], max_length=20, verbose_name='明细类型')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('abnormal_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_details', to='abnormal.abnormalsample', verbose_name='关联异常样品')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('solution_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='issue.issuesolutionrecord', verbose_name='所属解决记录')),
                ('test_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_details', to='testing.testitem', verbose_name='关联测试项')),
            ],
            options={
                'verbose_name': '问题解决明细',
                'verbose_name_plural': '问题解决明细',
                'ordering': ['created_at'],
            },
        ),
    ]
