# Generated by Django 6.0.3 on 2026-07-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_remove_issuesolutionrecord_abnormal_sample_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuesolutionrecord',
            name='title',
        ),
    ]
