# Generated by Django 5.2.13 on 2026-07-28 06:08

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_test_item(apps, schema_editor):
    IssueSolutionDetail = apps.get_model('issue', 'IssueSolutionDetail')
    for detail in IssueSolutionDetail.objects.exclude(test_item=None):
        detail.test_items.add(detail.test_item)


def reverse_copy_legacy_test_item(apps, schema_editor):
    IssueSolutionDetail = apps.get_model('issue', 'IssueSolutionDetail')
    for detail in IssueSolutionDetail.objects.all():
        first = detail.test_items.first()
        if first:
            detail.test_item = first
            detail.save(update_fields=['test_item'])
        detail.test_items.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0008_alter_abnormallogfile_file'),
        ('issue', '0009_remove_issuesolutionrecord_title'),
        ('testing', '0015_add_testitem_source_sankey_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesolutiondetail',
            name='test_items',
            field=models.ManyToManyField(blank=True, related_name='solution_details', to='testing.testitem', verbose_name='关联测试项'),
        ),
        migrations.AlterField(
            model_name='issuesolutiondetail',
            name='abnormal_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_details_legacy', to='abnormal.abnormalsample', verbose_name='关联异常样品（旧）'),
        ),
        migrations.AlterField(
            model_name='issuesolutiondetail',
            name='detail_type',
            field=models.CharField(choices=[('troubleshooting', '排查记录'), ('root_cause', '根因结果'), ('solution', '解决方案'), ('verification', '验证记录')], max_length=20, verbose_name='明细类型'),
        ),
        migrations.AlterField(
            model_name='issuesolutiondetail',
            name='test_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_details_legacy', to='testing.testitem', verbose_name='关联测试项（旧）'),
        ),
        migrations.RunPython(copy_legacy_test_item, reverse_copy_legacy_test_item),
    ]
