# Generated by Django 5.2.13 on 2026-08-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_issuesolutiondetail_test_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='summary',
            field=models.CharField(default='', max_length=200, verbose_name='问题概述'),
        ),
    ]
