# Generated by Django 5.2.13 on 2026-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_issue_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='jira_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Jira编号'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p1', max_length=10, verbose_name='优先级'),
        ),
    ]
