# Generated by Django 5.2.13 on 2026-04-26 09:22

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='主控型号')),
                ('description', models.TextField(blank=True, verbose_name='型号描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主控型号',
                'verbose_name_plural': '主控型号',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Flash型号')),
                ('description', models.TextField(blank=True, verbose_name='型号描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Flash型号',
                'verbose_name_plural': 'Flash型号',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PCBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='PCB型号')),
                ('description', models.TextField(blank=True, verbose_name='型号描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'PCB型号',
                'verbose_name_plural': 'PCB型号',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_number', models.CharField(editable=False, max_length=100, unique=True, verbose_name='方案编号')),
                ('flash_count', models.PositiveIntegerField(default=0, verbose_name='Flash数量')),
                ('software_version', models.CharField(max_length=50, verbose_name='软件版本')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('status', models.CharField(choices=[('alpha', 'Alpha'), ('beta', 'Beta'), ('release', 'Release')], default='alpha', max_length=10, verbose_name='状态')),
                ('software_file', models.FileField(blank=True, help_text='ZIP格式附件', null=True, upload_to='solutions/software/%Y/%m/', verbose_name='软件')),
                ('production_data', models.FileField(blank=True, help_text='ZIP格式附件', null=True, upload_to='solutions/production/%Y/%m/', verbose_name='生产资料')),
                ('test_report', models.FileField(blank=True, help_text='PDF格式附件', null=True, upload_to='solutions/reports/%Y/%m/', verbose_name='测试报告')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='方案描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('controller_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solution.controllermodel', verbose_name='主控型号')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_solutions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('flash_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solution.flashmodel', verbose_name='Flash型号')),
                ('pcb_models', models.ManyToManyField(blank=True, to='solution.pcbmodel', verbose_name='PCB型号')),
            ],
            options={
                'verbose_name': '方案',
                'verbose_name_plural': '方案',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='solution.solution', verbose_name='方案')),
            ],
            options={
                'verbose_name': '方案评论',
                'verbose_name_plural': '方案评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作')),
                ('old_status', models.CharField(blank=True, max_length=10, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=10, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='solution.solution', verbose_name='方案')),
            ],
            options={
                'verbose_name': '方案日志',
                'verbose_name_plural': '方案日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
