# Generated by Django 5.2.13 on 2026-04-26 09:22

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abnormal', '0001_initial'),
        ('fae', '0001_initial'),
        ('solution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='测试项编号')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已结束')], default='not_started', max_length=20, verbose_name='测试状态')),
                ('test_content', models.CharField(choices=[('rdt', 'RDT'), ('burn_in', 'BurnInTest'), ('retention', 'Retention'), ('rebooter', 'Rebooter'), ('sleeper', 'Sleeper'), ('apl', 'APL'), ('sorting', 'Sorting'), ('performance', '性能测试')], max_length=20, verbose_name='测试内容')),
                ('total_samples', models.PositiveIntegerField(default=0, verbose_name='样品总数')),
                ('passed_samples', models.PositiveIntegerField(default=0, verbose_name='通过数量')),
                ('abnormal_samples_count', models.PositiveIntegerField(default=0, verbose_name='异常数量')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fae.customer', verbose_name='所属客户')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_items', to='solution.solution', verbose_name='测试方案')),
                ('tracker', models.ForeignKey(limit_choices_to={'role__in': ['fae', 'fae_leader']}, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_tests', to=settings.AUTH_USER_MODEL, verbose_name='跟踪人')),
            ],
            options={
                'verbose_name': '测试项',
                'verbose_name_plural': '测试项',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testing.testitem', verbose_name='测试项')),
            ],
            options={
                'verbose_name': '测试评论',
                'verbose_name_plural': '测试评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='testing.testitem', verbose_name='测试项')),
            ],
            options={
                'verbose_name': '测试项日志',
                'verbose_name_plural': '测试项日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAbnormalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('abnormal_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abnormal.abnormalsample', verbose_name='异常样品')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_relations', to='testing.testitem', verbose_name='测试项')),
            ],
            options={
                'verbose_name': '测试异常关联',
                'verbose_name_plural': '测试异常关联',
                'unique_together': {('test_item', 'abnormal_sample')},
            },
        ),
    ]
