# Generated by Django 6.0.3 on 2026-06-02 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_testitem_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('initial', '初始测试'), ('passed', '通过分支'), ('failed', '失败/异常分支')], default='', max_length=20, verbose_name='分支类型'),
        ),
        migrations.AddField(
            model_name='testitem',
            name='source_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_tests', to='testing.testitem', verbose_name='来源测试项'),
        ),
    ]
