# Generated by Django 6.0.3 on 2026-06-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_testitem_branch_type_testitem_source_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testitem',
            name='source_test',
        ),
        migrations.AddField(
            model_name='testitem',
            name='source_tests',
            field=models.ManyToManyField(blank=True, related_name='derived_tests', to='testing.testitem', verbose_name='来源测试项'),
        ),
    ]
