# Generated by Django 6.0.3 on 2026-06-02 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fae', '0004_loganalyzerkeyword'),
        ('testing', '0004_remove_testitem_source_test_testitem_source_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SankeyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='节点标签')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='样品数量')),
                ('node_type', models.CharField(choices=[('initial', '初始'), ('pass', '通过'), ('fail', '失败'), ('subcategory', '子分类'), ('merged', '合流')], default='initial', max_length=20, verbose_name='节点类型')),
                ('category_reason', models.CharField(blank=True, max_length=100, verbose_name='分类原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fae_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sankey_nodes', to='fae.faetask', verbose_name='所属FAE任务')),
                ('parent_nodes', models.ManyToManyField(blank=True, related_name='child_nodes', to='testing.sankeynode', verbose_name='父节点')),
                ('test_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sankey_nodes', to='testing.testitem', verbose_name='关联测试项')),
            ],
            options={
                'verbose_name': '桑基图节点',
                'verbose_name_plural': '桑基图节点',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SankeyEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='流标签')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='流转数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fae_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sankey_edges', to='fae.faetask', verbose_name='所属FAE任务')),
                ('test_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sankey_edges', to='testing.testitem', verbose_name='关联测试项')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='testing.sankeynode', verbose_name='源节点')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='testing.sankeynode', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '桑基图流',
                'verbose_name_plural': '桑基图流',
                'ordering': ['created_at'],
            },
        ),
    ]
