# Generated by Django 6.0.3 on 2026-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0004_abnormalsample_is_edited_individually_and_more'),
        ('testing', '0005_sankeynode_sankeyedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sankeynode',
            name='abnormal_samples',
            field=models.ManyToManyField(blank=True, related_name='sankey_nodes', to='abnormal.abnormalsample', verbose_name='关联异常样品'),
        ),
    ]
