# Generated by Django 6.0.3 on 2026-06-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_sankeynode_abnormal_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='参数名称')),
                ('param_key', models.CharField(max_length=50, unique=True, verbose_name='参数标识')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('data_type', models.CharField(choices=[('integer', '整数'), ('float', '浮点数'), ('string', '字符串')], default='string', max_length=10, verbose_name='数据类型')),
                ('description', models.TextField(blank=True, verbose_name='参数说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '测试参数定义',
                'verbose_name_plural': '测试参数定义',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestItemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='参数值')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='testing.testitem', verbose_name='测试项')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testparameterdefinition', verbose_name='参数定义')),
            ],
            options={
                'verbose_name': '测试项参数值',
                'verbose_name_plural': '测试项参数值',
                'ordering': ['parameter__order', 'parameter__id'],
                'unique_together': {('test_item', 'parameter')},
            },
        ),
    ]
