# Generated by Django 6.0.3 on 2026-06-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_testparameterdefinition_testitemparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sankeynode',
            name='custom_y',
            field=models.FloatField(blank=True, help_text='用户手动拖拽的Y位置，为空则自动布局', null=True, verbose_name='自定义Y坐标'),
        ),
    ]
