# Generated by Django 6.0.3 on 2026-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_sankeynode_custom_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='retesting_samples',
            field=models.PositiveIntegerField(default=0, verbose_name='复测中数量'),
        ),
        migrations.AddField(
            model_name='testitem',
            name='testing_samples',
            field=models.PositiveIntegerField(default=0, verbose_name='测试中数量'),
        ),
    ]
