# Generated by Django 6.0.3 on 2026-06-21 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_testitem_retesting_samples_testitem_testing_samples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='异常原因')),
                ('description', models.TextField(blank=True, verbose_name='原因说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '异常原因',
                'verbose_name_plural': '异常原因',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestItemAbnormalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('description', models.TextField(blank=True, verbose_name='详细说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_analyses', to=settings.AUTH_USER_MODEL, verbose_name='分析人')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.abnormalreason', verbose_name='异常原因')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_analyses', to='testing.testitem', verbose_name='测试项')),
            ],
            options={
                'verbose_name': '异常样品分析',
                'verbose_name_plural': '异常样品分析',
                'ordering': ['-created_at'],
            },
        ),
    ]
