# Generated by Django 6.0.3 on 2026-06-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_abnormalreason_testitemabnormalanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sankeynode',
            name='node_type',
            field=models.CharField(choices=[('initial', '初始'), ('pass', '通过'), ('fail', '失败'), ('subcategory', '子分类'), ('abnormal_category', '异常分类'), ('merged', '合流')], default='initial', max_length=20, verbose_name='节点类型'),
        ),
    ]
