# Generated by Django 6.0.3 on 2026-06-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_alter_sankeynode_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitemabnormalanalysis',
            name='sankey_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_analyses', to='testing.sankeynode', verbose_name='关联桑基图节点'),
        ),
    ]
