# Generated by Django 6.0.3 on 2026-06-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_testitemabnormalanalysis_sankey_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='sample_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='样品来源'),
        ),
    ]
