# Generated by Django 6.0.3 on 2026-06-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_testitem_sample_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameterdefinition',
            name='default_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='默认值'),
        ),
    ]
