# Generated by Django 5.2.13 on 2026-07-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_testparameterdefinition_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='source_sankey_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_test_items', to='testing.sankeynode', verbose_name='来源桑基图节点'),
        ),
    ]
