# Generated by Django 5.2.13 on 2026-07-30 12:09

import django.db.models.deletion
from django.db import migrations, models


LEGACY_CHOICES = [
    ('rdt', 'RDT'),
    ('burn_in', 'BurnInTest'),
    ('retention', 'Retention'),
    ('rebooter', 'Rebooter'),
    ('sleeper', 'Sleeper'),
    ('apl', 'APL'),
    ('sorting', 'Sorting'),
    ('performance', '性能测试'),
]


def create_test_contents(apps, schema_editor):
    TestContent = apps.get_model('testing', 'TestContent')
    for code, name in LEGACY_CHOICES:
        TestContent.objects.get_or_create(code=code, defaults={'name': name})


def migrate_test_content_values(apps, schema_editor):
    TestItem = apps.get_model('testing', 'TestItem')
    TestContent = apps.get_model('testing', 'TestContent')
    content_map = {tc.code: tc.pk for tc in TestContent.objects.all()}
    for item in TestItem.objects.exclude(test_content_old=''):
        pk = content_map.get(item.test_content_old)
        if pk:
            item.test_content_id = pk
            item.save(update_fields=['test_content'])


def reverse_migrate_test_content_values(apps, schema_editor):
    TestItem = apps.get_model('testing', 'TestItem')
    for item in TestItem.objects.exclude(test_content=None):
        item.test_content_old = item.test_content.code
        item.save(update_fields=['test_content_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_add_testitem_source_sankey_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试内容',
                'verbose_name_plural': '测试内容',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(create_test_contents, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='testitem',
            old_name='test_content',
            new_name='test_content_old',
        ),
        migrations.AddField(
            model_name='testitem',
            name='test_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_items', to='testing.testcontent', verbose_name='测试内容'),
        ),
        migrations.RunPython(migrate_test_content_values, reverse_migrate_test_content_values),
        migrations.RemoveField(
            model_name='testitem',
            name='test_content_old',
        ),
    ]
