# Generated by Django 5.2.13 on 2026-04-26 09:22

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '异常样品评论',
                'verbose_name_plural': '异常样品评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '异常样品日志',
                'verbose_name_plural': '异常样品日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('fw_running', 'FW Running Log'), ('fw_nlog', 'FW Nlog'), ('fw_info', 'FW Info'), ('fw_power_on', 'FW Power On Log'), ('fw_memory_dump', 'FW Memory Dump'), ('rdt_running', 'RDT Running Log'), ('rdt_all_flush', 'RDT All Flush Log'), ('rdt_detail', 'RDT Detail'), ('other', '其他')], max_length=20, verbose_name='日志类型')),
                ('file', models.FileField(upload_to='abnormal/logs/%Y/%m/', verbose_name='日志文件')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '日志文件',
                'verbose_name_plural': '日志文件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AbnormalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='样品编号')),
                ('status', models.CharField(choices=[('pending_analysis', '待分析'), ('retesting', '复测中'), ('resolved', '已解决')], default='pending_analysis', max_length=20, verbose_name='当前状态')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('normal', '一般')], default='normal', max_length=20, verbose_name='优先级')),
                ('logs_collected', models.JSONField(blank=True, default=list, help_text='选择的日志类型列表', verbose_name='日志获取')),
                ('abnormal_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='异常描述')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '异常样品',
                'verbose_name_plural': '异常样品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='记录内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试记录条目',
                'verbose_name_plural': '测试记录条目',
                'ordering': ['-record_time'],
            },
        ),
    ]
