# Generated by Django 5.2.13 on 2026-04-26 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abnormal', '0001_initial'),
        ('fae', '0001_initial'),
        ('solution', '0001_initial'),
        ('testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='abnormallog',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='abnormallogfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='abnormalsample',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_abnormals', to=settings.AUTH_USER_MODEL, verbose_name='分析负责人'),
        ),
        migrations.AddField(
            model_name='abnormalsample',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_abnormals', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='abnormalsample',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fae.customer', verbose_name='所属客户'),
        ),
        migrations.AddField(
            model_name='abnormalsample',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_samples', to='solution.solution', verbose_name='样品方案'),
        ),
        migrations.AddField(
            model_name='abnormalsample',
            name='test_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_samples', to='testing.testitem', verbose_name='所属测试'),
        ),
        migrations.AddField(
            model_name='abnormallogfile',
            name='abnormal_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to='abnormal.abnormalsample', verbose_name='异常样品'),
        ),
        migrations.AddField(
            model_name='abnormallog',
            name='abnormal_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='abnormal.abnormalsample', verbose_name='异常样品'),
        ),
        migrations.AddField(
            model_name='abnormalcomment',
            name='abnormal_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='abnormal.abnormalsample', verbose_name='异常样品'),
        ),
        migrations.AddField(
            model_name='testrecordentry',
            name='abnormal_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_records', to='abnormal.abnormalsample', verbose_name='异常样品'),
        ),
        migrations.AddField(
            model_name='testrecordentry',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
    ]
