# Generated by Django 6.0.3 on 2026-06-01 16:11

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0003_abnormalsample_project'),
        ('fae', '0004_loganalyzerkeyword'),
        ('project', '0002_activitytimeline_subtitle'),
        ('solution', '0002_solution_project'),
        ('testing', '0002_testitem_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalsample',
            name='is_edited_individually',
            field=models.BooleanField(default=False, verbose_name='是否单独编辑过'),
        ),
        migrations.CreateModel(
            name='AbnormalSampleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='组编号')),
                ('status', models.CharField(choices=[('pending_analysis', '待分析'), ('retesting', '复测中'), ('resolved', '已解决')], default='pending_analysis', max_length=20, verbose_name='当前状态')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('normal', '一般')], default='normal', max_length=20, verbose_name='优先级')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='样品数量')),
                ('abnormal_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='异常描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_groups', to=settings.AUTH_USER_MODEL, verbose_name='分析负责人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fae.customer', verbose_name='所属客户')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_groups', to='project.project', verbose_name='所属项目')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_groups', to='solution.solution', verbose_name='样品方案')),
                ('test_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_groups', to='testing.testitem', verbose_name='所属测试')),
            ],
            options={
                'verbose_name': '异常样品组',
                'verbose_name_plural': '异常样品组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='abnormalsample',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='abnormal.abnormalsamplegroup', verbose_name='所属组'),
        ),
    ]
