# Generated by Django 6.0.3 on 2026-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0004_abnormalsample_is_edited_individually_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormallogfile',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='日志文件URL'),
        ),
        migrations.AlterField(
            model_name='abnormallogfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='abnormal/logs/%Y/%m/', verbose_name='日志文件'),
        ),
    ]
