# Generated by Django 6.0.3 on 2026-06-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0005_abnormallogfile_file_url_alter_abnormallogfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalsample',
            name='abnormal_summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='异常概述'),
        ),
        migrations.AddField(
            model_name='abnormalsamplegroup',
            name='abnormal_summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='异常概述'),
        ),
    ]
