# Generated by Django 6.0.3 on 2026-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0006_abnormalsample_abnormal_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormallogfile',
            name='folder_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='文件夹名'),
        ),
    ]
