# Generated by Django 6.0.3 on 2026-07-24 10:03

import abnormal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0007_abnormallogfile_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormallogfile',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=abnormal.models.abnormal_log_upload_path, verbose_name='日志文件'),
        ),
    ]
