# Generated by Django 5.2.13 on 2026-08-26 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnormal', '0008_alter_abnormallogfile_file'),
        ('issue', '0011_issue_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalsample',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_samples', to='issue.issue', verbose_name='关联问题单'),
        ),
    ]
