# Generated by Django 6.0.3 on 2026-04-26 11:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fae', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='物料编号')),
                ('name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('category', models.CharField(choices=[('ssd', 'SSD样品'), ('board', '主板/PCB'), ('chip', '芯片/颗粒'), ('tool', '工具/设备'), ('other', '其他')], default='ssd', max_length=20, verbose_name='类别')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='fae.customer', verbose_name='归属方')),
            ],
            options={
                'verbose_name': '物料档案',
                'verbose_name_plural': '物料档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('warehouse_type', models.CharField(choices=[('company', '公司仓库'), ('customer', '客户仓库')], max_length=20, verbose_name='仓库类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='fae.customer', verbose_name='关联客户')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['warehouse_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='调拨编号')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('transfer_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='调拨日期')),
                ('tracking_info', models.CharField(blank=True, help_text='可选，记录快递单号等辅助信息', max_length=100, verbose_name='物流信息/快递单号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='sample_shipment.samplematerial', verbose_name='物料')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transfers', to='sample_shipment.warehouse', verbose_name='来源仓库')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transfers', to='sample_shipment.warehouse', verbose_name='目标仓库')),
            ],
            options={
                'verbose_name': '物料流转记录',
                'verbose_name_plural': '物料流转记录',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sample_shipment.samplematerial', verbose_name='物料')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sample_shipment.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库库存',
                'verbose_name_plural': '仓库库存',
                'ordering': ['-quantity'],
                'unique_together': {('warehouse', 'material')},
            },
        ),
    ]
