# Generated by Django 5.2.13 on 2026-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_shipment', '0002_samplematerial_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplematerial',
            name='status',
            field=models.CharField(choices=[('returned', '归还'), ('borrowed', '借用'), ('scrapped', '报废'), ('lost', '丢失')], default='returned', max_length=20, verbose_name='状态'),
        ),
    ]
