# Generated by Django 6.0.3 on 2026-04-27 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fae', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('on_hold', '已暂停')], default='active', max_length=20, verbose_name='项目状态')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='fae.customer', verbose_name='关联客户')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('status_change', '状态变更'), ('comment', '评论'), ('transfer', '调拨')], max_length=20, verbose_name='操作类型')),
                ('module_type', models.CharField(max_length=30, verbose_name='模块类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='记录ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activities', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目活动记录',
                'verbose_name_plural': '项目活动记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
