# Generated by Django 6.0.3 on 2026-04-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytimeline',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='副标题/概述'),
        ),
    ]
