# Generated by Django 6.0.3 on 2026-06-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_activitytimeline_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityTimeline',
        ),
    ]
