# Generated by Django 6.0.3 on 2026-07-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_delete_activitytimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='单位：%', max_digits=5, null=True, verbose_name='当前良率'),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('import', '导入阶段'), ('pilot', '试产阶段'), ('mass_production', '量产阶段')], default='import', max_length=20, verbose_name='项目阶段'),
        ),
        migrations.AddField(
            model_name='project',
            name='sample_total_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='样品总数量'),
        ),
        migrations.AddField(
            model_name='project',
            name='yield_type',
            field=models.CharField(blank=True, choices=[('estimated', '估算良率'), ('calculated', '计算良率')], max_length=20, verbose_name='良率类型'),
        ),
    ]
