# Generated by Django 6.0.3 on 2026-07-24 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_current_yield_project_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_yield',
        ),
        migrations.RemoveField(
            model_name='project',
            name='yield_type',
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='方案名称')),
                ('yield_value', models.DecimalField(blank=True, decimal_places=2, help_text='单位：%', max_digits=5, null=True, verbose_name='良率')),
                ('yield_type', models.CharField(blank=True, choices=[('estimated', '估算良率'), ('calculated', '计算良率')], max_length=20, verbose_name='良率类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '生产方案',
                'verbose_name_plural': '生产方案',
                'ordering': ['-created_at'],
            },
        ),
    ]
