# Generated by Django 6.0.3 on 2026-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_current_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='production_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='单位：颗', verbose_name='生产数量'),
        ),
    ]
