# Generated by Django 5.2.13 on 2026-08-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_productionplan_production_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='current_software_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='当前软件版本'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='flash_quality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Flash质量'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='project',
            name='nand_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='NAND型号'),
        ),
    ]
