# Generated by Django 5.2.13 on 2026-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_productionplan_current_software_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='production_status',
            field=models.CharField(blank=True, choices=[('testing', '测试中'), ('debugging', '调试中'), ('in_production', '生产中'), ('delivered', '已交付'), ('on_hold', '暂停')], max_length=20, verbose_name='生产状态'),
        ),
    ]
