# Generated by Django 5.2.13 on 2026-04-26 09:22

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fae', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RDRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='需求编号')),
                ('requirement_type', models.CharField(choices=[('hardware', '硬件需求'), ('software', '软件需求'), ('flash_debug', '颗粒调试')], max_length=20, verbose_name='需求类型')),
                ('priority', models.CharField(choices=[('p0', 'P0 - 阻塞性问题'), ('p1', 'P1 - 重要需求'), ('p2', 'P2 - 一般优先')], default='p2', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('rd_confirming', '研发确认中'), ('customer_confirming', '客户确认中'), ('in_progress', '进行中'), ('paused', '暂停中'), ('customer_verifying', '客户验证中'), ('archived', '已归档')], default='rd_confirming', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='需求描述')),
                ('report_date', models.DateField(verbose_name='截至/汇报日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='截止时间')),
                ('delay_risk', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='low', max_length=10, verbose_name='延期风险')),
                ('delay_reason', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='延期原因')),
                ('jira_number', models.CharField(blank=True, max_length=50, verbose_name='Jira编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(limit_choices_to={'role__in': ['rd', 'rd_leader']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requirements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rd_requirements', to='fae.customer', verbose_name='关联客户')),
                ('related_fae_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rd_requirements', to='fae.faetask', verbose_name='关联FAE任务')),
            ],
            options={
                'verbose_name': '研发需求',
                'verbose_name_plural': '研发需求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requirements/attachments/%Y/%m/', verbose_name='附件')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rd_requirement.rdrequirement', verbose_name='需求')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '需求附件',
                'verbose_name_plural': '需求附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rd_requirement.rdrequirement', verbose_name='需求')),
            ],
            options={
                'verbose_name': '需求评论',
                'verbose_name_plural': '需求评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rd_requirement.rdrequirement', verbose_name='需求')),
            ],
            options={
                'verbose_name': '需求操作日志',
                'verbose_name_plural': '需求操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField(default=django.utils.timezone.now, verbose_name='汇报日期')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='进展内容')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='进度百分比')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='汇报人')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='rd_requirement.rdrequirement', verbose_name='需求')),
            ],
            options={
                'verbose_name': '需求进展记录',
                'verbose_name_plural': '需求进展记录',
                'ordering': ['-progress_date', '-created_at'],
            },
        ),
    ]
